name: Oli cat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - working-directory: $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: cat
      run: cat * >> GRPluginStands.txt
    - uses: aTable/deploy-to-dropbox@v1.0.7
