name: Oli cat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cat
      working-directory: $GITHUB_WORKSPACE/
      run: cat ./* >> GRPluginStands.txt
    - uses: aTable/deploy-to-dropbox@v1.0.7
