name: Oli cat

on:
  push:
    paths-ignore: 
      - 'GRPluginStands.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cat
      run: cat $GITHUB_WORKSPACE/* >> GRPluginStands.txt
    - name: ls
      run: ls -al $GITHUB_WORKSPACE
    - name: push
      uses: ludeeus/action-push@0.0.1

