name: Oli cat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cat
      run: cat $GITHUB_WORKSPACE/* >> GRPluginStands.txt
    - name: ls
      working-directory: $GITHUB_WORKSPACE
      run: ls -al
    - name:  deploy
      uses: aTable/deploy-to-dropbox@v1.0.7
